import { ThemeProvider } from '@/contexts/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Urbanist } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const urbanist = Urbanist({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        {/* <ProgressBarProvider>*/}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem> 
        {children}
        </ThemeProvider>
    {/*   </ProgressBarProvider> */}
      </body>
    </html>
  )
}
